# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4a7712f672fbcae7d2eebe41fd4914e0878bf5b47f31e2650c274b970e2da110598e686bc63c309eddf043c33e481204a20afed216cd9fd4a3295f248af612fe

test:
  secret_key_base: a5774badbf15cb9952e57cdfc931b2f3482e255d54a9b0c20de9f448e02b60c3f27d3de3a92119400b91fd99203b64c9a6d68e25af69a09ef3977666fb2a60ed

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
